"""add_state_to_cases

Revision ID: 5bb77e272f48
Revises: a08093ecc213
Create Date: 2026-09-05 21:39:22.165150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb77e272f48'
down_revision: Union[str, Sequence[str], None] = 'a08093ecc213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('state', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'state')
    # ### end Alembic commands ###
