"""Add risk_level and explanation to Prediction

Revision ID: a08093ecc213
Revises: 50bf48ad60b6
Create Date: 2026-09-05 20:16:05.843300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08093ecc213'
down_revision: Union[str, Sequence[str], None] = '50bf48ad60b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('risk_level', sa.String(length=50), nullable=True))
    op.add_column('predictions', sa.Column('explanation', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'explanation')
    op.drop_column('predictions', 'risk_level')
    # ### end Alembic commands ###
