"""Reconcile schema drift and add backup_assignee

Revision ID: baab7db3eede
Revises: 554d1d5f7c19
Create Date: 2026-09-08 18:24:39.530120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baab7db3eede'
down_revision: Union[str, Sequence[str], None] = '554d1d5f7c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interventions_due_at'), table_name='interventions')
    op.drop_index(op.f('ix_interventions_priority'), table_name='interventions')
    op.drop_column('interventions', 'due_at')
    op.drop_column('interventions', 'priority')
    op.drop_column('interventions', 'completed_at')
    op.drop_column('interventions', 'assigned_role')
    op.drop_column('interventions', 'acknowledged_at')
    op.drop_column('interventions', 'reason')
    op.drop_column('interventions', 'assigned_at')
    op.drop_column('outcomes', 'notes')
    op.drop_column('outcomes', 'follow_up_required')
    op.add_column('interventions', sa.Column('backup_assignee', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcomes', sa.Column('follow_up_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('outcomes', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('interventions', 'backup_assignee')
    op.add_column('interventions', sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('interventions', sa.Column('reason', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('interventions', sa.Column('acknowledged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('interventions', sa.Column('assigned_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('interventions', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('interventions', sa.Column('priority', sa.VARCHAR(length=20), server_default=sa.text("'ROUTINE'::character varying"), autoincrement=False, nullable=False))
    op.add_column('interventions', sa.Column('due_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_interventions_priority'), 'interventions', ['priority'], unique=False)
    op.create_index(op.f('ix_interventions_due_at'), 'interventions', ['due_at'], unique=False)
    # ### end Alembic commands ###
